apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - kubernetes.docker.internal/
    secretName: tls-secret
  rules:
  #- host: map.douglasham.com
    - http:
        paths:
        - backend:
            serviceName: aks-helloworld-one
            servicePort: 80
          path: /hello-world-one(/|$)(.*)
        - backend:
            serviceName: mapgameapi-service
            servicePort: 443
          path: /api(/|$)(.*)
        - backend:
            serviceName: mapgame-service
            servicePort: 80
          path: /()(.*)
